spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ipldb
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
# logging:
#   level:
#     org.springframework.orm.jpa: debug
#     org.hibernate: debug
